"use client";

import * as React from "react";
import { Download, FolderDown, Loader2, Pause, Play, X } from "lucide-react";

type Asset = { id: string; type: string; originalFilename: string | null; label: string | null };
const labels: Record<string, string> = { PREVIEW: "Preview", MASTER: "Master", STEM: "Stem", ALTERNATE: "Versión alternativa", DELIVERABLE: "Entregable" };

export default function AdminAssetDownloads({ trackId, assets }: { trackId: string; assets: Asset[] }) {
  const [open, setOpen] = React.useState(false); const [pending, setPending] = React.useState<string | null>(null); const [playing, setPlaying] = React.useState<string | null>(null); const [error, setError] = React.useState<string | null>(null); const audio = React.useRef<HTMLAudioElement | null>(null);
  React.useEffect(() => () => audio.current?.pause(), []);
  async function urlFor(asset: Asset, attachment = false) { const response = await fetch(`/api/tracks/${trackId}/assets/${asset.id}/download${attachment ? "?disposition=attachment" : ""}`); const json = await response.json().catch(() => null); if (!response.ok || !json?.url) throw new Error(json?.error ?? "No fue posible preparar el archivo."); return json.url as string; }
  async function togglePlay(asset: Asset) { if (playing === asset.id) { audio.current?.pause(); setPlaying(null); return; } setPending(asset.id); setError(null); try { audio.current?.pause(); const source = await urlFor(asset); const next = new Audio(source); audio.current = next; next.addEventListener("ended", () => setPlaying(null)); next.addEventListener("error", () => { setError("Este formato no se puede reproducir en el navegador."); setPlaying(null); }); await next.play(); setPlaying(asset.id); } catch (reason) { setError(reason instanceof Error ? reason.message : "No fue posible reproducir el archivo."); } finally { setPending(null); } }
  async function download(asset: Asset) { setPending(asset.id); setError(null); try { const url = await urlFor(asset, true); const link = document.createElement("a"); link.href = url; link.target = "_blank"; link.rel = "noopener noreferrer"; document.body.appendChild(link); link.click(); link.remove(); } catch (reason) { setError(reason instanceof Error ? reason.message : "No fue posible descargar el archivo."); } finally { setPending(null); } }
  if (!assets.length) return null;
  return <aside className="fixed bottom-32 left-1/2 z-50 w-[min(46rem,calc(100vw-2rem))] -translate-x-1/2 print:hidden">
    {open ? <div className="overflow-hidden rounded-xl border border-primary/40 bg-background/95 shadow-2xl backdrop-blur"><header className="flex items-center justify-between border-b border-border px-4 py-3"><div><p className="text-[10px] font-semibold tracking-[.14em] text-primary uppercase">Solo administración</p><h2 className="text-sm font-semibold">Descargas de prueba</h2></div><button aria-label="Cerrar descargas" onClick={() => { audio.current?.pause(); setPlaying(null); setOpen(false); }} className="rounded p-1 hover:bg-muted"><X className="h-4 w-4"/></button></header><div className="grid max-h-[46vh] gap-2 overflow-auto p-3 sm:grid-cols-2">{assets.map((asset) => <article key={asset.id} className="flex min-w-0 items-center gap-3 rounded-lg border border-border bg-card/60 p-3"><button aria-label={playing === asset.id ? `Pausar ${labels[asset.type] ?? asset.type}` : `Reproducir ${labels[asset.type] ?? asset.type}`} disabled={Boolean(pending)} onClick={() => togglePlay(asset)} className="grid h-9 w-9 shrink-0 place-items-center rounded-full border border-border hover:bg-muted disabled:opacity-50">{pending === asset.id ? <Loader2 className="h-4 w-4 animate-spin"/> : playing === asset.id ? <Pause className="h-4 w-4"/> : <Play className="h-4 w-4"/>}</button><div className="min-w-0 flex-1"><p className="text-xs font-semibold">{labels[asset.type] ?? asset.type}</p><p className="truncate text-[11px] text-muted-foreground">{asset.label || asset.originalFilename || "Archivo"}</p></div><button aria-label={`Descargar ${labels[asset.type] ?? asset.type}`} disabled={Boolean(pending)} onClick={() => download(asset)} className="grid h-9 w-9 shrink-0 place-items-center rounded-md border border-border hover:bg-muted disabled:opacity-50"><Download className="h-4 w-4"/></button></article>)}</div>{error && <p className="border-t border-destructive/30 px-4 py-2 text-xs text-destructive">{error}</p>}</div> : <button onClick={() => setOpen(true)} className="mx-auto flex items-center gap-2 rounded-full border border-primary/50 bg-background/95 px-4 py-2 text-xs font-semibold shadow-lg backdrop-blur hover:bg-muted"><FolderDown className="h-4 w-4 text-primary"/>Descargas de prueba</button>}
  </aside>;
}
