"use client";
import * as React from "react";
import { FileAudio, Loader2, Star, UploadCloud } from "lucide-react";

type Asset = { id: string; type: "MASTER"|"PREVIEW"|"STEM"|"ALTERNATE"|"DELIVERABLE"; access: string; status: string; isCurrent: boolean; originalFilename: string | null; label: string | null; mime: string | null; sizeBytes: bigint | null; createdAt: Date; storageKey: string };
const names = { PREVIEW: "Preview público", MASTER: "Master", STEM: "Stem", ALTERNATE: "Versión alternativa", DELIVERABLE: "Entregable" };
function bytes(value: bigint | null) { return value == null ? "—" : `${(Number(value) / 1024 / 1024).toFixed(2)} MB`; }

export function TrackAssetsModule({ track }: { track: { id: string; isDraft: boolean; assets: Asset[] } }) {
  const [type, setType] = React.useState<Asset["type"]>("MASTER"); const [file, setFile] = React.useState<File | null>(null); const [label, setLabel] = React.useState(""); const [pending, setPending] = React.useState(false); const [message, setMessage] = React.useState<string | null>(null);
  const uploadType = (value: Asset["type"]) => { setType(value); setFile(null); setLabel(""); setMessage(null); };
  async function upload() {
    if (!file) return setMessage("Selecciona un archivo.");
    setPending(true); setMessage("Preparando subida segura…");
    try {
      const sign = await fetch("/api/uploads/sign", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ trackId: track.id, assetType: type, fileName: file.name, label: label || undefined, mime: file.type, size: file.size }) });
      const signed = await sign.json().catch(() => null); if (!sign.ok || !signed?.url) throw new Error(signed?.error ?? "No se pudo preparar la subida.");
      setMessage("Subiendo a R2…"); const put = await fetch(signed.url, { method: "PUT", headers: signed.headers, body: file }); if (!put.ok) throw new Error("R2 rechazó el archivo.");
      const complete = await fetch("/api/uploads/complete", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ uploadToken: signed.uploadToken }) }); const json = await complete.json().catch(() => null); if (!complete.ok) throw new Error(json?.error ?? "No se pudo vincular el archivo.");
      setMessage(json?.job ? "Archivo vinculado y enviado a procesamiento." : "Archivo privado vinculado correctamente."); setFile(null); setLabel(""); window.location.reload();
    } catch (error) { setMessage(error instanceof Error ? error.message : "Error inesperado."); } finally { setPending(false); }
  }
  async function makeCurrent(asset: Asset) { setPending(true); try { const r = await fetch(`/api/tracks/${track.id}/assets/${asset.id}/current`, { method: "POST" }); const j = await r.json().catch(() => null); if (!r.ok) throw new Error(j?.error ?? "No se pudo actualizar."); setMessage(`${names[asset.type]} vigente actualizado y enviado a procesamiento.`); window.location.reload(); } catch (e) { setMessage(e instanceof Error ? e.message : "Error inesperado."); } finally { setPending(false); } }
  const preview = track.assets.filter((a) => a.type === "PREVIEW"); const privateAssets = track.assets.filter((a) => a.type !== "PREVIEW");
  return <div className="max-w-6xl space-y-4"><section className="rounded-xl border border-border bg-card p-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-primary">{track.isDraft ? "Borrador privado" : "Track publicado"}</p><h2 className="mt-1 text-lg font-semibold">Archivos del track</h2></div><p className="max-w-md text-sm text-muted-foreground">Preview público; masters, stems y entregables privados con historial.</p></div></section>
    <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(20rem,.8fr)]"><section className="rounded-xl border border-border bg-card p-4"><div className="flex items-center justify-between gap-3"><h3 className="font-semibold">Preview público</h3><button onClick={() => uploadType("PREVIEW")} className={`rounded-md px-3 py-2 text-sm ${type === "PREVIEW" ? "bg-primary text-primary-foreground" : "border border-border"}`}>Reemplazar preview</button></div><AssetList assets={preview} onCurrent={makeCurrent} pending={pending}/></section>
    <section className="rounded-xl border border-border bg-card p-4"><h3 className="font-semibold">Assets privados</h3><p className="mt-1 text-xs text-muted-foreground">El master vigente se procesa; las correcciones quedan en historial.</p><div className="mt-3 flex flex-wrap gap-2">{(["MASTER","STEM","ALTERNATE","DELIVERABLE"] as const).map((value) => <button key={value} onClick={() => uploadType(value)} className={`rounded-md px-3 py-2 text-sm ${type === value ? "bg-primary text-primary-foreground" : "border border-border"}`}>{names[value]}</button>)}</div></section></div>
    <section className="rounded-xl border border-border bg-card p-4"><h3 className="font-semibold">Historial privado</h3><AssetList assets={privateAssets} onCurrent={makeCurrent} pending={pending}/></section>
    <section className="max-w-3xl rounded-xl border border-border bg-card p-4"><div className="flex items-center gap-2"><UploadCloud className="h-5 w-5 text-primary"/><h3 className="font-semibold">Subir {names[type]}</h3></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="space-y-1"><span className="text-xs text-muted-foreground">Etiqueta opcional</span><input value={label} onChange={(e) => setLabel(e.target.value)} className="h-10 w-full rounded-md border border-border bg-background px-3" placeholder={type === "STEM" ? "Ej. Drums" : "Ej. Master v2"}/></label><label className="flex cursor-pointer items-center justify-center rounded-md border border-dashed border-border px-3 py-2 text-sm"><FileAudio className="mr-2 h-4 w-4"/>{file?.name ?? "Elegir archivo"}<input className="sr-only" type="file" accept="audio/*" onChange={(e) => setFile(e.target.files?.[0] ?? null)}/></label></div><button disabled={!file || pending} onClick={upload} className="mt-4 inline-flex h-10 items-center gap-2 rounded-md bg-foreground px-4 text-sm font-semibold text-background disabled:opacity-40">{pending ? <Loader2 className="h-4 w-4 animate-spin"/> : <UploadCloud className="h-4 w-4"/>}Subir y vincular</button></section>{message && <p role="status" className="max-w-3xl rounded-lg border border-border bg-muted/30 p-3 text-sm">{message}</p>}</div>;
}
function AssetList({ assets, onCurrent, pending }: { assets: Asset[]; onCurrent: (asset: Asset) => void; pending: boolean }) { if (!assets.length) return <p className="mt-3 text-sm text-muted-foreground">Aún no hay archivos.</p>; return <div className="mt-3 grid gap-2 xl:grid-cols-2">{assets.map((asset) => <div key={asset.id} className="flex min-w-0 items-center gap-3 rounded-lg border border-border p-3 text-sm"><FileAudio className="h-4 w-4 shrink-0 text-muted-foreground"/><div className="min-w-0 flex-1"><p className="truncate font-medium">{asset.label || asset.originalFilename || asset.storageKey.split("/").at(-1)}</p><p className="truncate text-xs text-muted-foreground">{names[asset.type]} · {bytes(asset.sizeBytes)} · {asset.access === "PUBLIC" ? "Público" : "Privado"}</p></div>{asset.isCurrent ? <span className="inline-flex shrink-0 items-center gap-1 rounded-full bg-emerald-500/10 px-2 py-1 text-xs text-emerald-700"><Star className="h-3 w-3"/>Vigente</span> : (asset.type === "MASTER" || asset.type === "PREVIEW") ? <button disabled={pending} onClick={() => onCurrent(asset)} className="shrink-0 rounded-md border border-border px-2 py-1 text-xs disabled:opacity-40">Marcar vigente</button> : null}</div>)}</div>; }
